version: "3.9"

services:
  backend:
    container_name: backend
    build:
      context: .
    networks:
      - express-mongo
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo:5.0.6
    restart: always
    # ports:
    #   - 27017:27017
    networks:
      - express-mongo
    volumes:
      - data:/data/db
volumes:
  data:
  appLogs:
networks:
  express-mongo:
